var modules =
[
    [ "Hardware Abstraction Layer", "group__hal__doc.html", "group__hal__doc" ],
    [ "SPI Hardware Abstraction Layer for CC3200", "group__hal__spi__cc3200.html", "group__hal__spi__cc3200" ],
    [ "HAL general configuration for dsPIC33EV256GM102", "group__hal__general__dspic33ev256gm102.html", null ],
    [ "HAL ADC Module", "group__hal__adc.html", null ],
    [ "HAL Keyfob Receiver Module", "group__hal__keyfob.html", null ],
    [ "SPI Hardware Abstraction Layer for MSP430F5529", "group__hal__spi__msp430f5529.html", "group__hal__spi__msp430f5529" ],
    [ "SPI Hardware Abstraction Layer for MSP432P401R", "group__hal__spi__msp432p401r.html", null ],
    [ "SPI Hardware Abstraction Layer for PIC24FJ256GA110", "group__hal__spi__pic24fj256ga110.html", "group__hal__spi__pic24fj256ga110" ],
    [ "SPI Hardware Abstraction Layer for PIC32MX250F128B", "group__hal__spi__pic32mx250f128b.html", "group__hal__spi__pic32mx250f128b" ],
    [ "SPI Hardware Abstraction Layer for PIC32MX695F512H", "group__hal__spi__pic32mx695f512h.html", "group__hal__spi__pic32mx695f512h" ],
    [ "ADC Module", "group__adc__module.html", "group__adc__module" ],
    [ "FIFO Byte Buffer", "group__buffer.html", "group__buffer" ],
    [ "Game Management / Helper Module", "group__game.html", "group__game" ],
    [ "List Module", "group__list.html", "group__list" ],
    [ "Macros", "group__macros.html", "group__macros" ],
    [ "Muhlbaier's Game", "group__muh__game.html", "group__muh__game" ],
    [ "nRF24L01+ Module", "group__n_r_f24.html", "group__n_r_f24" ],
    [ "nRF24L01+ Network (geared for class projects)", "group__nrf24network.html", null ],
    [ "Generate random integer in a given range", "group__random__int.html", "group__random__int" ],
    [ "Subsystem Module", "group__subsystem.html", "group__subsystem" ],
    [ "Terminal Helper Functions", "group__terminal.html", "group__terminal" ],
    [ "Timing module", "group__timing.html", "group__timing" ],
    [ "UART Module", "group__uart.html", "group__uart" ],
    [ "ESP8266 WiFi", "group__esp8266.html", "group__esp8266" ],
    [ "Integer Definitions", "group__int__def.html", "group__int__def" ],
    [ "JSON Parser", "group__json__parser.html", "group__json__parser" ],
    [ "Task Management Module", "group__task.html", "group__task" ]
];